---
- name: Setup and run PXE boot server
  hosts: pxeserver
  become: true
  vars_files:
    - ./vars/vars.yml

  handlers:
    - name: Restart network interface
      ansible.builtin.service:
        name: networking
        state: restarted

    - name: Restart TFTP
      ansible.builtin.service:
        name: "{{ TFTPD }}"
        state: restarted

    - name: Restart DHCP
      ansible.builtin.service:
        name: "{{ DHCPD }}"
        state: restarted

    - name: Restart nftables
      ansible.builtin.service:
        name: "{{ NFTABLES }}"
        state: restarted
  
  pre_tasks:
    - name: Load package variables (dynamically)
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/packages_{{ ansible_facts['os_family'] }}.yml"
        - "vars/packages_default.yml"
    
    - name: Set DHCP interface and server IP when using single interface
      ansible.builtin.set_fact:
        DHCP_INTERFACE: "{{ PRIMARY_INTERFACE }}"
        SERVER_IP: "{{ ansible_facts['default_ipv4']['address'] }}"
      when: USE_PXE_INTERFACE is false
    - name: Set DHCP interface and server IP when using pxe interface
      ansible.builtin.set_fact:
        DHCP_INTERFACE: "{{ PXE_INTERFACE }}"
        SERVER_IP: "{{ GATEWAY_IP }}"
      when: USE_PXE_INTERFACE

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - "{{ DHCPD }}"
          - "{{ TFTPD }}"
          - "{{ APACHE }}"
          - "{{ NANO }}"
          - "{{ UNZIP }}"
          - "{{ NET_TOOLS }}"
          - "{{ NFTABLES }}"
          - "{{ RSYNC }}"
        state: latest
    
    - name: Configure secondary network interface using a template file (Debian)
      ansible.builtin.template:
        src: ./templates/pxe-iface.j2
        dest: /etc/network/interfaces.d/{{ PXE_INTERFACE }}.cfg
        owner: root
        group: root
        mode: '0644'
      when: 
        - USE_PXE_INTERFACE
        - ansible_facts['os_family'] == 'Debian'
      register: secondary_iface_result
      notify:
        - Restart network interface
        - Restart TFTP
      
    - name: Enable secondary network interface
      ansible.builtin.command: "ifup {{ PXE_INTERFACE }}"
      when: secondary_iface_result.changed

    - name: Make sure TFTP directory exists
      ansible.builtin.file:
        path: "{{ TFTP_ROOT }}"
        state: directory
        mode: '0755'
    
    - name: Configure TFTP to use set root directory
      ansible.builtin.lineinfile:
        path: "/etc/default/{{ TFTPD }}"
        regexp: "TFTP_DIRECTORY="
        line: 'TFTP_DIRECTORY="{{ TFTP_ROOT }}"'
        state: present
      notify:
        - Restart TFTP
    
    - name: Move pxe files to TFTP directory
      ansible.builtin.copy:
        src: ./Boot/
        dest: "{{ TFTP_ROOT }}"
        mode: '0755'

    - name: Configure DHCP interface (isc-dhcp-server)
      ansible.builtin.lineinfile:
        path: "/etc/default/{{ DHCPD }}"
        regexp: "{{ item.regexp }}"
        line: "{{item.line}}"
        state: present
      with_items:
        - regexp: "DHCPDv4_CONF="
          line: "DHCPDv4_CONF=/etc/dhcp/dhcpd.conf"
        - regexp: "INTERFACESv4="
          line: 'INTERFACESv4="{{ DHCP_INTERFACE }}"'
      when: DHCPD == "isc-dhcp-server"
      notify:
        - Restart DHCP
    
    - name: Configure DHCP server (isc-dhcp-server)
      ansible.builtin.template:
        src: ./templates/dhcpd.j2
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: '0644'
      when: DHCPD == "isc-dhcp-server"
      notify:
        - Restart DHCP
    
    - name: Configure DHCP server
      ansible.builtin.template:
        src: ./templates/kea-dhcp4.j2
        dest: /etc/kea/kea-dhcp4.conf
        owner: root
        group: root
        mode: '0644'
      when: DHCPD == "kea-dhcp4-server"
      notify:
        - Restart DHCP

    - name: Process ISOs and create iPXE menu
      ansible.builtin.import_tasks: ./tasks/iso_and_ipxe_menu.yml

    - name: Enable IP passthrough
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
        state: present
        reload: true
      when: USE_PXE_INTERFACE
    
    - name: write ipv4 rules into rules.v4
      ansible.builtin.template:
        src: ./templates/nftables.j2
        dest: /etc/nftables.conf
        owner: root
        group: root
        mode: '0640'
      notify: Restart nftables
      when: USE_PXE_INTERFACE
    
    - name: enable TFTP
      ansible.builtin.service:
        name: "{{ TFTPD }}"
        enabled: true
        state: started
    
    - name: enable dhcp server
      ansible.builtin.service:
        name: "{{ DHCPD }}"
        enabled: true
        state: started
    
    - name: enable apache2
      ansible.builtin.service:
        name: "{{ APACHE }}"
        enabled: true
        state: started

    - name: enable nftables
      ansible.builtin.service:
        name: "{{ NFTABLES }}"
        enabled: true
        state: started
      when: USE_PXE_INTERFACE
    
    - name: Allow http service through firewalld
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
      when: ansible_facts['os_family'] == 'RedHat'
