---
- name: Setup and run PXE boot server
  hosts: pxeserver
  become: true
  vars_files:
    - ./vars/vars.yml

  handlers:
    - name: Restart network interface
      ansible.builtin.service:
        name: networking
        state: restarted

    - name: Restart TFTP
      ansible.builtin.service:
        name: "{{ TFTPD }}"
        state: restarted

    - name: Restart DHCP
      ansible.builtin.service:
        name: "{{ DHCPD }}"
        state: restarted

    - name: Restart nftables
      ansible.builtin.service:
        name: "{{ NFTABLES }}"
        state: restarted
  
  pre_tasks:
    - name: Load package variables (dynamically)
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/packages_{{ ansible_facts['os_family'] }}.yml"
        - "vars/packages_default.yml"
    
    - name: Set DHCP interface and server IP when using single interface
      ansible.builtin.set_fact:
        DHCP_INTERFACE: "{{ PRIMARY_INTERFACE }}"
        SERVER_IP: "{{ ansible_facts['default_ipv4']['address'] }}"
      when: USE_PXE_INTERFACE is false
    - name: Set DHCP interface and server IP when using pxe interface
      ansible.builtin.set_fact:
        DHCP_INTERFACE: "{{ PXE_INTERFACE }}"
        SERVER_IP: "{{ GATEWAY_IP }}"
      when: USE_PXE_INTERFACE

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - "{{ NANO }}"
          - "{{ UNZIP }}"
          - "{{ NET_TOOLS }}"
          - "{{ NFTABLES }}"
        state: latest
    
    - name: Configure secondary (PXE) network interface
      ansible.builtin.import_tasks: ./tasks/pxe_iface.yml
      when: USE_PXE_INTERFACE

    - name: Setup TFTP server
      ansible.builtin.import_tasks: ./tasks/tftp_server.yml

    - name: Setup DHCP server
      ansible.builtin.import_tasks: ./tasks/dhcp_server.yml
    
    - name: Setup Apache server
      ansible.builtin.import_tasks: ./tasks/apache.yml

    - name: Process ISOs and create iPXE menu
      ansible.builtin.import_tasks: ./tasks/iso_and_ipxe_menu.yml

    - name: Enable IP passthrough
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
        state: present
        reload: true
      when: USE_PXE_INTERFACE
    
    - name: write ipv4 rules into rules.v4
      ansible.builtin.template:
        src: ./templates/nftables.j2
        dest: /etc/nftables.conf
        owner: root
        group: root
        mode: '0640'
      notify: Restart nftables
      when: USE_PXE_INTERFACE

    - name: enable nftables
      ansible.builtin.service:
        name: "{{ NFTABLES }}"
        enabled: true
        state: started
      when: USE_PXE_INTERFACE

