---
- name: Setup and run PXE boot server
  hosts: pxeserver
  become: true
  vars_files:
    - ./vars/vars.yml
    - ./vars/dont_edit.yml
  pre_tasks:
    - name: Load package variables (dynamically)
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/packages_{{ ansible_facts['os_family'] }}.yml"
        - "vars/packages_default.yml"
  tasks:
    - name: Create image content directory
      ansible.builtin.import_tasks: ./tasks/iso_and_ipxe_menu.yml
