---
- name: Setup and run PXE boot server
  hosts: pxeserver
  become: true
  vars_files:
    - ./vars/vars.yml
  
  pre_tasks:
    - name: Load package variables (dynamically)
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/packages_{{ ansible_facts['os_family'] }}.yml"
        - "vars/packages_default.yml"
    
    - name: Set server IP when using single interface
      ansible.builtin.set_fact:
        SERVER_IP: "{{ ansible_facts['default_ipv4']['address'] }}"
      when: USE_PXE_INTERFACE is false
    - name: Set server IP when using pxe interface
      ansible.builtin.set_fact:
        SERVER_IP: "{{ GATEWAY_IP }}"
      when: USE_PXE_INTERFACE

  tasks:
    - name: Create image content directory
      ansible.builtin.file:
        path: "{{ IMAGES_CONTENT }}"
        state: directory
        mode: '0755'
    
    - name: Create ISO directory
      ansible.builtin.file:
        path: "{{ ISO_IMAGES }}"
        state: directory
        mode: '0755'
    
    - name: Create ISO mount directory
      ansible.builtin.file:
        path: /media/ISO
        state: directory
        mode: '0755'

    # loop to process ISOs
    - name: Process ISOs
      ansible.builtin.include_tasks: ./tasks/process_iso.yml
      loop: "{{ isos }}"
      loop_control:
        loop_var: iso
        label: "{{ iso.folder_name }}"
      when: iso.enabled | default(true) | bool

    - name: iPXE menu
      ansible.builtin.template:
        src: ./templates/ipxe.menu.j2
        dest: "{{ WEB_ROOT }}/ipxe.menu"
        owner: root
        group: root
        mode: '0644'
